# Generated by Django 2.2.2 on 2022-02-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
