# Generated by Django 2.2.2 on 2022-02-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220221_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
